### ISSUE TITLE
Tests: Add invalid template

### ISSUE THREAD

**Issue by alexbaumgertner** [easy-deep-learning/mvc-pure-js#14]
Add invalid template test — this template should throw Error when rendered
http://chaijs.com/api/bdd/#method_throw

**Comment by dmitrylebedev** [comment]
А может проще будет сделать так? 

```javascript
  it('match(regexp)', function(){
    testView = new View('<div><%= name %></div>');
    testViewTemplateSource = testView.templateSource;

    testViewTemplateSource.should.match(/%>/);

  });
```

**Comment by alexbaumgertner** [comment]
Нам нужно протестировать, что будет в случае
```js
var testView = new View('<div><%= name </div>'); //  шаблон без `%>`  специально
testView.render({name: 'test'})
```
то есть, как мы обрабатываем ошибки — не валится ли вся программа, информативный ли лог.

**Comment by dmitrylebedev** [comment]
В этом случае мы получим ошибку, потому что в случае нашего приложения это недопустимо и программа повалится с ошибкой: `Uncaught SyntaxError: Unexpected token =`

```javascript
  it('should be invalid template', function () {

    var err = new ReferenceError('Uncaught SyntaxError: Unexpected token =');

    testView = new View('<%= name');
    var testData = { name: 'test' };
    var result = testView.render(testData);

    expect(result).to.throw(err);


  });
```
Т.е мойт тест валится с ошибкой. Что я передаю в конструктор `trow` не так?

**Comment by alexbaumgertner** [comment]
нужно так:
```js
expect(result).to.throw(function() {
  testView.render(testData);
});
```

А для улучшения, мы должны сделать обработку ошибок в шаблоне. Сейчас сделаю прототип.

**Comment by alexbaumgertner** [comment]
@dmitrylebedev Сделал прототип https://github.com/easy-deep-learning/mvc-pure-js/pull/16

**Comment by dmitrylebedev** [comment]
Ок. Я понял, что в expect я должен передавать функцию с неправильными данными из шаблона.
А что должно быть в Error? Как раз обработка ошибок? 
Я плохо понимаю, что дальше делать, по-моему тест сейчас не работает как надо.

**Comment by alexbaumgertner** [comment]
Error — это глобальный объект ошибки, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error
В js можно сделать свою обработку ошибок в коде — прописать сообщения и тд.

Попробуй выполнить в консоли `throw Error('Не правильный код')`

**Comment by alexbaumgertner** [comment]
@dmitrylebedev Вот хорошая статья https://learn.javascript.ru/oop-errors

**Comment by dmitrylebedev** [comment]
@alexbaumgertner, да, я так делал:
`var err = new ReferenceError('Uncaught SyntaxError: Unexpected token =');`

Что нужно сделать помимо этого?

**Comment by alexbaumgertner** [comment]
Выбросить ошибку:
`throw err`

**Comment by dmitrylebedev** [comment]
Нет, валится с ошибкой:

```javascript
  it('should throw error with invalid template', function () {
    testView = new View('<%= name'); // template is not closed
    var err = new Error('Uncaught SyntaxError: Unexpected token =');

    var testData = {name: 'test'};
    var renderRunner = function () {
      testView.render(testData);
    };

    expect(renderRunner).to.throw(err);
  });
```

`PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 4 of 4 (1 FAILED) (0 secs / 0.004 secs)`
   ` ✗ should throw error with invalid template`
       ` expected [Function] to throw 'Error: Uncaught SyntaxError: Unexpected token =' but 'SyntaxError:`
` Unexpected token \'=\'' was thrown`

**Comment by alexbaumgertner** [comment]
@dmitrylebedev 
https://learn.javascript.ru/oop-errors
![error 2016-03-12 23-13-08](https://cloud.githubusercontent.com/assets/223620/13725040/068538dc-e8a8-11e5-8dbc-c60f5066972e.png)


https://learn.javascript.ru/oop-errors#instanceof-try-catch
![monosnap 2016-03-12 23-30-20](https://cloud.githubusercontent.com/assets/223620/13725156/844c4a2e-e8aa-11e5-89eb-63a371336d8f.png)
