### ISSUE TITLE
Add Router description

### ISSUE THREAD

**Issue by dmitrylebedev** [easy-deep-learning/mvc-pure-js#22]
Add API description.
Add tests https://github.com/easy-deep-learning/mvc-pure-js/issues/20

1) `route` – добавить новый _путь_
2) ...

**Comment by alexbaumgertner** [comment]
Посмотри 
- http://joakim.beng.se/blog/posts/a-javascript-router-in-20-lines.html
- http://microjs.com/#router

**Comment by alexbaumgertner** [comment]
Задачи роутинга 
— по определенному url вызвать определенный метод и передать ему параметры из URL;
— по названию метода, и параметрам сделать url (обратный процесс пп1)

**Comment by alexbaumgertner** [comment]
Вот хороший пример API
https://github.com/alexmingoia/koa-router

**Comment by alexbaumgertner** [comment]
Тут https://github.com/easy-deep-learning/mvc-pure-js/issues/22#issuecomment-204791185 даже проще.

**Comment by alexbaumgertner** [comment]
Take a look https://github.com/easy-deep-learning/mvc-pure-js/pull/23
