### ISSUE TITLE
Tests: Add View unit tests

### ISSUE THREAD

**Issue by alexbaumgertner** [easy-deep-learning/mvc-pure-js#4]
## Description 
- [x] template init
- [x] render simple template
- [x] render template with js instructions
- [x] invalid templates

Code: https://github.com/easy-deep-learning/mvc-pure-js/blob/master/tests/view.spec.js

**Comment by alexbaumgertner** [comment]
Нужно добавить тесты шаблонов с js внутри, то есть не только `<div><%=  name %>`
но и 
```js
<% dataItems.forEach(function(item) { %>
  <%= item %>
<%  }); %>
```

**Comment by alexbaumgertner** [comment]
Также следует добавить тест невалидного шаблона:
```js
// не закрыта скобка
<%= item 
```

и шаблона с невалидным js
```js
<% undefined.forEach(function(item) { %>
```

**Comment by dmitrylebedev** [comment]
>Нужно добавить тесты шаблонов с js внутри, то есть не только <div><%= name %>
но и

Нужно обновить текущий тест или дописать новое правило? 

```javascript
 it('should set template', function() {
    testView = new View('<% dataItems.forEach(function(item) { %> + ''
  <%= item %>  + ''
<%  }); %> ');

    expect(typeof testView.template).to.equal('function');
  });
```

**Comment by dmitrylebedev** [comment]
Разобрался. _Не смог удалить предыдущий вопрос_
